# pyright: reportUnusedCallResult=false
"""init db

Revision ID: 001
Revises: 
Create Date: 2026-05-15 20:57:13.683900+03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('message_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recipient_selector', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('selected_channel_codes', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('priority', sa.Text(), server_default=sa.text("'normal'"), nullable=False),
    sa.Column('create_idempotency_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("priority IN ('low', 'normal', 'high')", name='ck_campaigns_priority'),
    sa.CheckConstraint("status IN ('running', 'completed', 'partially_failed', 'failed', 'cancelling', 'cancelled')", name='ck_campaigns_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channels',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('adapter_name', sa.Text(), server_default=sa.text("'stub'"), nullable=False),
    sa.Column('provider_code', sa.Text(), nullable=True),
    sa.Column('queue_group', sa.Text(), nullable=False),
    sa.Column('rate_limits', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("jsonb_build_object('rps', 10, 'maxConcurrency', 10)"), nullable=False),
    sa.Column('retry_policy', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("jsonb_build_object('maxAttempts', 5, 'baseDelaySeconds', 30, 'maxDelaySeconds', 1800)"), nullable=False),
    sa.Column('disable_policy', sa.Text(), server_default=sa.text("'retry_later'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("disable_policy IN ('retry_later', 'fail_fast')", name='ck_channels_disable_policy'),
    sa.CheckConstraint("queue_group IN ('email', 'sms', 'push', 'messenger')", name='ck_channels_queue_group'),
    sa.CheckConstraint("state IN ('enabled', 'disabled', 'degraded')", name='ck_channels_state'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('idempotency_keys',
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('request_hash', sa.Text(), nullable=False),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('processing', 'completed', 'failed')", name='ck_idempotency_keys_status'),
    sa.PrimaryKeyConstraint('scope', 'key')
    )
    op.create_table('outbox_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('region_id', sa.Text(), server_default=sa.text("'default'"), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exchange', sa.Text(), server_default=sa.text("'notification.direct'"), nullable=False),
    sa.Column('routing_key', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('dedupe_key', sa.Text(), nullable=False),
    sa.Column('locked_by', sa.Text(), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'publishing', 'published', 'failed')", name='ck_outbox_events_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('region_id', sa.Text(), server_default=sa.text("'default'"), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive', 'blocked')", name='ck_users_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('campaign_region_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('region_id', sa.Text(), server_default=sa.text("'default'"), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('fanout_lock_owner', sa.Text(), nullable=True),
    sa.Column('fanout_lock_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fanout_attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('fanout_pending', 'fanout_running', 'fanout_completed', 'fanout_failed')", name='ck_campaign_region_runs_status'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'region_id', name='uq_campaign_region_runs_campaign_region')
    )
    op.create_table('campaign_stats',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('total_tasks', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('queued', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('sending', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('succeeded', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('failed', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('retry_scheduled', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('dead_lettered', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('cancelled', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    op.create_table('user_channels',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('verified', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive')", name='ck_user_channels_status'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'channel_id', 'address', name='uq_user_channels_user_channel_address')
    )
    op.create_table('delivery_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('campaign_region_run_id', sa.UUID(), nullable=False),
    sa.Column('region_id', sa.Text(), server_default=sa.text("'default'"), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_channel_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('channel_code', sa.Text(), nullable=False),
    sa.Column('queue_group', sa.Text(), nullable=False),
    sa.Column('recipient_address_snapshot', sa.Text(), nullable=False),
    sa.Column('message_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('priority', sa.Text(), server_default=sa.text("'normal'"), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lease_owner', sa.Text(), nullable=True),
    sa.Column('lease_token', sa.UUID(), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_code', sa.Text(), nullable=True),
    sa.Column('provider_request_id', sa.Text(), nullable=True),
    sa.Column('last_error_code', sa.Text(), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'sending', 'succeeded', 'failed', 'retry_scheduled', 'dead_lettered', 'cancelled')", name='ck_delivery_tasks_status'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['campaign_region_run_id'], ['campaign_region_runs.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['user_channel_id'], ['user_channels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('delivery_attempts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Text(), nullable=True),
    sa.Column('channel_code', sa.Text(), nullable=False),
    sa.Column('provider_code', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_type', sa.Text(), nullable=True),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('provider_request_id', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("error_type IS NULL OR error_type IN ('transient', 'permanent', 'unknown')", name='ck_delivery_attempts_error_type'),
    sa.CheckConstraint("status IN ('started', 'succeeded', 'failed', 'timed_out', 'stale')", name='ck_delivery_attempts_status'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['delivery_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'attempt_no', name='uq_delivery_attempts_task_attempt_no')
    )
    op.create_table('dlq_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('channel_code', sa.Text(), nullable=False),
    sa.Column('reason_code', sa.Text(), nullable=False),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'open'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_replayed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('open', 'replayed', 'ignored')", name='ck_dlq_items_status'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['delivery_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dlq_items')
    op.drop_table('delivery_attempts')
    op.drop_table('delivery_tasks')
    op.drop_table('user_channels')
    op.drop_table('campaign_stats')
    op.drop_table('campaign_region_runs')
    op.drop_table('users')
    op.drop_table('outbox_events')
    op.drop_table('idempotency_keys')
    op.drop_table('channels')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
